export const PLAYER_STARTING_LEVEL = 1;
export const PLAYER_STARTING_EXPERIENCE = 0;
export const PLAYER_BASE_EXPERIENCE_TO_LEVEL = 5;
export const PLAYER_EXPERIENCE_TO_LEVEL_STEP = 5;

export const EXPERIENCE_ORB_POOL_SIZE = 96;
export const EXPERIENCE_ORB_RADIUS = 6;
export const EXPERIENCE_ORB_COLLECT_RADIUS = 24;
export const EXPERIENCE_ORB_ATTRACT_RADIUS = 60;
export const EXPERIENCE_ORB_ATTRACT_SPEED = 420;
export const EXPERIENCE_ORB_IDLE_DRIFT_SPEED = 42;
export const EXPERIENCE_ORB_IDLE_DRIFT_DURATION_MS = 220;
export const EXPERIENCE_ORB_FILL_COLOR = 0x52ffe0;
export const EXPERIENCE_ORB_STROKE_COLOR = 0xe8fffb;
export const EXPERIENCE_ORB_STROKE_WIDTH = 2;
